[workspace]
version = "0.29.0"

[toolchain]
package_manager = "yarn"
anchor_version = "0.29.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
minimal_nft = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkgWRHPxMKP6S"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
